services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    # env_file:
    #   - ./.env
    
    volumes:
      - .:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=adhikari
      - DATABASE_NAME=fastapi
      - SECRET_KEY=cnlakjsndfklashjdfncvsakljhflsakd3453242safsadf2
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30  
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=adhikari
      - POSTGRES_DB=fastapi

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
